apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
stringData:
  GMAIL_ADDRESS: "devprojectssl@gmail.com" #enter your email to get the id
  GMAIL_PASSWORD: "ejsy txvn nukq ngnz"
type: Opaque

